---
- name: Join the other masters
  hosts: kubemasterjoin
  serial: 1
  tasks:
    - name: Turn Off swap
      become: true
      ansible.builtin.shell: "swapoff -a"
      changed_when: False  
    - name: Join the other masters
      become: true
      ansible.builtin.shell: "{{ JOIN_MASTER }}"
      register: masteradd
    - name: Result print
      debug:
        var: masteradd
    - name: Pause for 2 minutes
        ansible.builtin.pause:
          minutes: 2    
