---
- name: Initialize the Kubernetes Cluster from the first master node
  hosts: kubemaster
  tasks:
    - name: Turn Off swap
      become: true
      ansible.builtin.shell: "swapoff -a"
      changed_when: False
      ignore_errors: yes
    - name: Init master node
      become: true
      ansible.builtin.shell: "kubeadm init --pod-network-cidr {{ POD_NETWORK_CIDR }} --ignore-preflight-errors=Swap"
      ignore_errors: yes
      register: resultprint
    - name: Kubeadm init print
      debug:
        var: resultprint
    - name: Add dir .kube
      ansible.builtin.file:
        path: $HOME/.kube
        state: directory
        mode: '0755'
    - name: Copy kube config in home dir
      become: true
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ USER_ADM }}/.kube/config
        owner: "{{ USER_ADM }}"
        group: "{{ USER_ADM }}"
        mode: '0600'
        remote_src: true
    - name: Save the contents of join-command
      ansible.builtin.command: "kubeadm token create --print-join-command"
      register: jointoken
    - name: Kubeadm node print
      debug:
        var: jointoken
    - name: Pause for 4 minutes
      ansible.builtin.pause:
        minutes: 4
    - name: Deploy pod network
      ansible.builtin.shell: "kubectl apply -f {{ CNI_POD }}"
    - name: Reboot
      become: true
      ansible.builtin.reboot:
