---
- name: Preparation servers and install kubernetes
  hosts: all
  handlers:
    - name: Start modules overlay
      become: true
      ansible.builtin.command: "modprobe overlay"
    - name: Start modules br_netfilter
      become: true
      ansible.builtin.command: "modprobe br_netfilter"
    - name: Apply sysctl params
      become: true
      ansible.builtin.command: "sysctl --system"
    - name: Reboot
      become: true
      ansible.builtin.reboot:
  pre_tasks:
    - name: Save the contents of /etc/os-release
      command: cat /etc/os-release
      register: os_release
      changed_when: False
    - name: Detect Linux Servers
      debug:
        msg: "Find on CentOS|Fedora..."
      when: os_release.stdout.find('CentOS') != -1 or os_release.stdout.find('Fedora') != -1
      changed_when: False
    - name: Detect Linux Servers
      debug:
        msg: "Find on Debian|Ubuntu..."
      when: os_release.stdout.find('debian') != -1 or os_release.stdout.find('Ubuntu') != -1
      changed_when: False  
  tasks:
    - name: Turn Off swap
      become: true
      ansible.builtin.shell: "swapoff -a"
      changed_when: False
    - name: Add modules in core
      become: true
      ansible.builtin.template:
        src: "templates/k8s.conf"
        dest: "/etc/modules-load.d/k8s.conf"
      notify: 
        - Start modules overlay
        - Start modules br_netfilter
    - name: Add params sysctl
      become: true
      ansible.builtin.template:
        src: "templates/K8s.conf"
        dest: "/etc/sysctl.d/k8s.conf"    
      notify: Apply sysctl params
    - name: Disable SELinux
      become: true
      ansible.posix.selinux:
        state: disabled
    - name: Add repository CentOS
      become: true
      ansible.builtin.template:
        src: "templates/kubernetes-centos.repo"
        dest: "/etc/yum.repos.d/kubernetes-centos.repo"
      when: os_release.stdout.find('CentOS') != -1
    - name: Add repository Fedora
      become: true
      ansible.builtin.template:
        src: "templates/kubernetes-fedora.repo"
        dest: "/etc/yum.repos.d/kubernetes-fedora.repo"
      when: os_release.stdout.find('Fedora') != -1
  post_tasks:
    - name: Install kube packages
      become: true
      ansible.builtin.yum:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
        - containerd
        - kubelet
        - kubeadm
        - kubectl
      async: 600
      poll: 60
      when: os_release.stdout.find('CentOS') != -1 or os_release.stdout.find('Fedora') != -1      
    - name: Add config containerd
      become: true
      ansible.builtin.template:
        src: "templates/containerd_config.toml"
        dest: "/etc/containerd/config.toml"
        mode: '0644'
    - name: Add dir kubelet.service.d
      become: true
      ansible.builtin.file:
        path: "/etc/systemd/system/kubelet.service.d"
        state: directory
        mode: '0755'
    - name: Copy conf kubelet
      become: true
      ansible.builtin.template:
        src: "templates/20-allow-swap.conf"
        dest: "/etc/systemd/system/kubelet.service.d/20-allow-swap.conf"
        mode: '0644'
    - name: Add conf kubelet
      become: true
      lineinfile:
        create: no
        dest: "/usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf"
        insertafter: EOF
        line: 'Environment="KUBELET_EXTRA_ARGS=--fail-swap-on=false"'
    - name: update env kubelet
      become: true
      lineinfile:
        create: no
        dest: "/etc/sysconfig/kubelet"
        insertafter: EOF
        line: 'KUBELET_EXTRA_ARGS=--fail-swap-on=false' 
    - name: Start containerd
      become: true
      ansible.builtin.systemd:
        name: containerd
        enabled: true
        state: started
    - name: Start kubelet
      become: true
      ansible.builtin.systemd:
        name: kubelet
        enabled: true
        state: started
      notify: Reboot
