---
- name: Join Worker nodes
  hosts: kubenode
  serial: 1
  tasks:
    - name: Turn Off swap
      become: true
      ansible.builtin.shell: "swapoff -a"
      changed_when: False
    - name: reloaded kubelet
      become: true
      ansible.builtin.systemd:
        name: kubelet
        state: restarted
        daemon_reload: true
    - name: Join Worker nodes
      become: true
      ansible.builtin.shell: "{{ JOIN_WORKER }}"
      register: nodeadd
    - name: Result print
      debug:
        var: nodeadd
    - name: Pause for 1 minutes
      ansible.builtin.pause:
        minutes: 1
