all:
  hosts:
    kubemaster1:
      ansible_host: "192.168.2.30"
    kubemaster2:
      ansible_host: "192.168.2.9"
    kubemaster3:
      ansible_host: "192.168.2.23"
    kubenode1:
      ansible_host: "192.168.2.22"
    kubenode2:
      ansible_host: "192.168.2.11"
    kubenode3:
      ansible_host: "192.168.2.33"
    kubenode4:
      ansible_host: "192.168.2.37"
  children:
    kubemaster:
      hosts:
        kubemaster1:
    kubemasterjoin:
      hosts:
        kubemaster2:
        kubemaster3:        
    kubenode:
      hosts:
        kubenode1:
        kubenode2:
        kubenode3:
        kubenode4:
  vars:
    ansible_user: ansible
