all:
  hosts:
    kubemaster1:
      ansible_host: "192.168.2.140"
    kubemaster2:
      ansible_host: "192.168.2.183"
    kubemaster3:
      ansible_host: "192.168.2.227"
    kubenode1:
      ansible_host: "192.168.2.197"
    kubenode2:
      ansible_host: "192.168.2.15"
    kubenode3:
      ansible_host: "192.168.2.16"
    kubenode4:
      ansible_host: "192.168.2.17"
  children:
    kubemaster:
      hosts:
        kubemaster1:
    kubemasterjoin:
      hosts:
        kubemaster2:
        kubemaster3:        
    kubenode:
      hosts:
        kubenode1:
        kubenode2:
        kubenode3:
        kubenode4:
  vars:
    ansible_user: ansible