all:
  hosts:
    kubemaster:
      ansible_host: "192.168.2.220"
    kubenode1:
      ansible_host: "192.168.2."
    kubenode2:
      ansible_host: "192.168.2."
    kubenode3:
      ansible_host: "192.168.2."
    kubenode4:
      ansible_host: "192.168.2."
  children:
    kubemaster:
      hosts:
        kubemaster:     
    kubenode:
      hosts:
        kubenode1:
        kubenode2:
        kubenode3:
        kubenode4:
  vars:
    ansible_user: ansible
